version: "3"

services:
  sonarqube:
    image: sonarqube:9.2.3-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /tmp/opt/sonarqube/conf:/opt/sonarqube/conf \
      - /tmp/opt/sonarqube/logs:/opt/sonarqube/data \
      - /tmp/opt/sonarqube/data:/opt/sonarqube/logs \
      - /tmp/opt/sonarqube/extensions:/opt/sonarqube/extensions \
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      PGDATA: /var/lib/postgresql/data/pgdata