---
  - name: Install Docker
    shell: |
      apt-get update -y && apt-get install -y apt-transport-https
      curl -fsSL https://get.docker.com | bash
      sudo usermod -aG docker $USER

  - name: Check current docker-compose version.
    command: "{{ docker_compose_path }} --version"
    register: docker_compose_current_version
    check_mode: no
    changed_when: false
    failed_when: false

  - name: Delete existing docker-compose version if it's different.
    file:
      path: "{{ docker_compose_path }}"
      state: absent
    when: >
      docker_compose_current_version.stdout is defined
      and docker_compose_version not in docker_compose_current_version.stdout

  - name: Install Docker Compose (if configured).
    get_url:
      url: "{{ docker_compose_url }}"
      dest: "{{ docker_compose_path }}"
      mode: 0755
    when: >
      docker_compose_current_version.stdout is not defined
      or docker_compose_version not in docker_compose_current_version.stdout
    
  - name: "Login to DockerHub"
    command: "docker login -u {{ docker_username }} --password-stdin"
    args:
      stdin: "{{ docker_password }}"

  - name: "Habilitando a memoria"
    shell: sudo sysctl -w vm.max_map_count=262144

  - name: copy Docker Compose files
    copy:
      src: files/docker-compose.yml
      dest: /home/{{user}}/docker-compose.yml

  - name: deploy Docker Compose stack
    shell: |
      cd /home/{{user}}/
      sudo docker-compose up -d

  - name: validate containers
    shell: |
      cd /home/{{user}}/
      sudo docker container ls
